const sizes = { B: 1, KB: 1024, MB: 1048576, GB: 1073741824 }; // In bytes
export const expiresIn = "3 hours";
export const limitMB = 50;
export const limit = 50 * sizes.MB;
export const otpExpiry = 300000; // 5 minutes
export const announcementTypes = ["announcement", "call"] as const;
export const emailTypes = ["default", "confirm", "otp"] as const;
export const userTypes = ["satyam-admin", "satyam-chief-editor", "satyam-member", "reviewer", "author"] as const;
export const volumeTypes = ["accepting", "published"] as const;
